name: Nightly Package Tests
on:
  schedule:
    - cron: '30 10 * * *' # run at 10:30 AM UTC
  workflow_dispatch:  # to trigger manually

jobs:
  stable-min:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.12', '3.11' , '3.10', '3.9' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install hya

      - name: Run short experiment
        run: |
          python -c "import hya; from omegaconf import OmegaConf; " \
            "print(hya.registry.registry.state); " \
            "assert not hya.imports.is_torch_available(); " \
            "assert OmegaConf.create({'key': '\${hya.add:1,4}'}).key == 5"


  stable-all:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.12', '3.11' , '3.10', '3.9' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install "hya[all]"

      - name: Run short experiment
        run: |
          python -c "import hya; from omegaconf import OmegaConf; import torch; " \
            "print(hya.registry.registry.state); " \
            "assert hya.imports.is_torch_available(); " \
            "assert OmegaConf.create({'key': '\${hya.to_tensor:1.42}'}).key.equal(torch.tensor(1.42))"


  omegaconf:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11' , '3.10', '3.9' ]
        omegaconf-version: [ 2.3.0, 2.2.3, 2.1.2 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install hya

      - name: Install OmegaConf
        run: |
          pip install omegaconf==${{ matrix.omegaconf-version }}

      - name: Run short experiment
        run: |
          python -c "import hya; from omegaconf import OmegaConf; " \
            "print(hya.registry.registry.state); " \
            "assert not hya.imports.is_torch_available(); " \
            "assert OmegaConf.create({'key': '\${hya.add:1,4}'}).key == 5"


  braceexpand:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12', '3.11' , '3.10', '3.9' ]
        braceexpand-version: [ 0.1.7 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install hya

      - name: Install OmegaConf
        run: |
          pip install braceexpand==${{ matrix.braceexpand-version }}

      - name: Run short experiment
        run: |
          python -c "import hya; from omegaconf import OmegaConf; " \
            "print(hya.registry.registry.state); " \
            "assert not hya.imports.is_braceexpand_available(); " \
            "assert OmegaConf.create({'key': '\${hya.braceexpand:\{1..4\}}).key == ['1', '2', '3', '4']"


  torch:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.11' , '3.10', '3.9' ]
        torch-version: [ 2.1.1, 2.0.0, 1.13.1, 1.12.1, 1.11.0, 1.10.0 ]
        exclude:
          - torch-version: 1.10.0
            python-version: 3.10
          - torch-version: 1.10.0
            python-version: 3.11
          - torch-version: 1.11.0
            python-version: 3.11
          - torch-version: 1.12.1
            python-version: 3.11

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          pip install hya torch==${{ matrix.torch-version }}

      - name: Run short experiment
        run: |
          python -c "import hya; from omegaconf import OmegaConf; import torch; " \
            "print(hya.registry.registry.state); " \
            "assert hya.imports.is_torch_available(); " \
            "assert OmegaConf.create({'key': '\${hya.to_tensor:1.42}'}).key.equal(torch.tensor(1.42))"
